### ISSUE TITLE
Week 17 Tracking

### ISSUE THREAD

**Issue by vivianknee** [vivianknee/ssvgcarsFrontend#10]
- [x] Clone copy repository of leuck_reunion
- [x] Run local server of our copy: reunion_project
- [x] Customize site
- [x] Add in some tables
- [x] Change images
